/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.setERFrame;

import base.BaseErAiCheckData;
import config.Config;

/**
 *
 * @author wuxianshikong
 */
public class ErlistJPanel extends javax.swing.JPanel {
    long udid;
    OneDirectionFrame superView;
    /**
     * Creates new form ErlistJPanel
     */
    public ErlistJPanel() {
        initComponents();
    }
    public void updateListUI(BaseErAiCheckData baseErAiCheckData,long udid,OneDirectionFrame superView)
    {
        this.superView = superView;
        this.udid = udid;
        pt_L1.setText(Config.BTCPLAT[baseErAiCheckData.leftCheckData.Pt_L][0]);
        pt_R1.setText(Config.BTCPLAT[baseErAiCheckData.leftCheckData.Pt_R][0]);
        bs_L1.setText(Config.getStringBS(baseErAiCheckData.leftCheckData.bs_L));
        bs_R1.setText(Config.getStringBS(baseErAiCheckData.leftCheckData.bs_R));
        compare_L1.setText(Config.getHDStr(baseErAiCheckData.leftCheckData.gd));
        com.setText(Config.CONPARE_STR[baseErAiCheckData.compare]);
        String value;
        if(baseErAiCheckData.leftCheckData.han_bi == 0)
        {
            value = "当前最新价*"+baseErAiCheckData.leftCheckData.bi;
        }
        else
        {
            value = "" + baseErAiCheckData.leftCheckData.a+"*X+"+baseErAiCheckData.leftCheckData.b;
        }
        value1.setText(value);
        if(baseErAiCheckData.compare != Config.YHF_NULL)
        {
            pt_L2.setText(Config.BTCPLAT[baseErAiCheckData.rightCheckData.Pt_L][0]);
            pt_R2.setText(Config.BTCPLAT[baseErAiCheckData.rightCheckData.Pt_R][0]);
            bs_L2.setText(Config.getStringBS(baseErAiCheckData.rightCheckData.bs_L));
            bs_R2.setText(Config.getStringBS(baseErAiCheckData.rightCheckData.bs_R));
            compare_L2.setText(Config.getHDStr(baseErAiCheckData.rightCheckData.gd));
            String str;
            if(baseErAiCheckData.rightCheckData.han_bi == 0)
            {
                str = "当前最新价*"+baseErAiCheckData.leftCheckData.bi;
            }
            else
            {
                str = "" + baseErAiCheckData.rightCheckData.a+"*X+"+baseErAiCheckData.leftCheckData.b;
            }
            value2.setText(str);
        }
        else
        {
            pt_L2.setText("");
            pt_R2.setText("");
            bs_L2.setText("");
            bs_R2.setText("");
            compare_L2.setText("");
            value2.setText("");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pt_L1 = new javax.swing.JLabel();
        bs_L1 = new javax.swing.JLabel();
        compare_L1 = new javax.swing.JLabel();
        pt_R1 = new javax.swing.JLabel();
        bs_R1 = new javax.swing.JLabel();
        value1 = new javax.swing.JLabel();
        com = new javax.swing.JLabel();
        pt_L2 = new javax.swing.JLabel();
        bs_L2 = new javax.swing.JLabel();
        pt_R2 = new javax.swing.JLabel();
        compare_L2 = new javax.swing.JLabel();
        bs_R2 = new javax.swing.JLabel();
        value2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        pt_L1.setText("OKCoin中国");

        bs_L1.setText("期货现价");

        compare_L1.setText("高于");

        pt_R1.setText("OKCoin中国");

        bs_R1.setText("期货现价");

        value1.setText("当前最新价 X100%");

        com.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        com.setText("任一");

        pt_L2.setText("OKCoin中国");

        bs_L2.setText("期货现价");

        pt_R2.setText("OKCoin中国");

        compare_L2.setText("高于");

        bs_R2.setText("期货现价");

        value2.setText("当前最新价 X100%");

        jButton1.setText("撤销");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bs_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compare_L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt_R1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bs_R1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(value1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt_L2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bs_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compare_L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt_R2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bs_R2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(value2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt_L1)
                    .addComponent(bs_L1)
                    .addComponent(compare_L1)
                    .addComponent(pt_R1)
                    .addComponent(bs_R1)
                    .addComponent(value1)
                    .addComponent(com, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pt_L2)
                    .addComponent(bs_L2)
                    .addComponent(compare_L2)
                    .addComponent(pt_R2)
                    .addComponent(bs_R2)
                    .addComponent(value2)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        superView.mainController.removeProcessEr(this.udid);
        superView.updateListUI();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bs_L1;
    private javax.swing.JLabel bs_L2;
    private javax.swing.JLabel bs_R1;
    private javax.swing.JLabel bs_R2;
    private javax.swing.JLabel com;
    private javax.swing.JLabel compare_L1;
    private javax.swing.JLabel compare_L2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pt_L1;
    private javax.swing.JLabel pt_L2;
    private javax.swing.JLabel pt_R1;
    private javax.swing.JLabel pt_R2;
    private javax.swing.JLabel value1;
    private javax.swing.JLabel value2;
    // End of variables declaration//GEN-END:variables
}
