/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.setERFrame;

import base.BaseErData;
import javax.swing.JTabbedPane;

/**
 *
 * @author wuxianshikong
 */
public class ErPanal extends javax.swing.JPanel {
    public BaseErData baseErData;
    /**
     * Creates new form ErPanal
     */
    public ErPanal() {
        baseErData = new BaseErData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        pt_L = new javax.swing.JComboBox<>();
        bs_L = new javax.swing.JComboBox<>();
        pt_R = new javax.swing.JComboBox<>();
        bs_R = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bi_value = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        han_a = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        han_b = new javax.swing.JTextField();
        do_bs = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 153));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "高于", "低于", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        pt_L.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OK中国", "OK国际", "火币", "BtbVC", "比特币中国" }));
        pt_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt_LActionPerformed(evt);
            }
        });

        bs_L.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "现货买价", "现货卖价" }));
        bs_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs_LActionPerformed(evt);
            }
        });

        pt_R.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OK中国", "OK国际", "火币", "BtbVC", "比特币中国" }));
        pt_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt_RActionPerformed(evt);
            }
        });

        bs_R.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "现货买价", "现货卖价" }));
        bs_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bs_RActionPerformed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel5.setText("特定值 = 最新成交价 * ");

        bi_value.setText("00000");
        bi_value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bi_valueFocusLost(evt);
            }
        });
        bi_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bi_valueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bi_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bi_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("比例", jPanel2);

        jLabel6.setText("特定值 = ");

        han_a.setText("000000");
        han_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                han_aFocusLost(evt);
            }
        });
        han_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                han_aActionPerformed(evt);
            }
        });

        jLabel7.setText("*X + ");

        han_b.setText("1111111");
        han_b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                han_bFocusLost(evt);
            }
        });
        han_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                han_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(han_a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(han_b, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(han_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(han_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("函数", jPanel1);

        do_bs.setBackground(new java.awt.Color(0, 204, 102));
        do_bs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "买入", "卖出" }));
        do_bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_bsActionPerformed(evt);
            }
        });

        jLabel1.setText("操作");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(do_bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pt_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bs_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bs_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bs_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bs_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(do_bs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        baseErData.gd = jComboBox1.getSelectedIndex();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bi_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bi_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bi_valueActionPerformed

    private void han_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_han_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_han_aActionPerformed

    private void han_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_han_bActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_han_bActionPerformed

    private void pt_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt_LActionPerformed
        // TODO add your handling code here:
        baseErData.Pt_L =  pt_L.getSelectedIndex() + 1;
    }//GEN-LAST:event_pt_LActionPerformed

    private void pt_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt_RActionPerformed
        // TODO add your handling code here:
        baseErData.Pt_R =  pt_R.getSelectedIndex() + 1;
    }//GEN-LAST:event_pt_RActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if(jTabbedPane1 != null)
        {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            baseErData.han_bi = selectedIndex;
        }
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void bs_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs_LActionPerformed
        // TODO add your handling code here:
        baseErData.bs_L = bs_L.getSelectedIndex();
    }//GEN-LAST:event_bs_LActionPerformed

    private void bs_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bs_RActionPerformed
        // TODO add your handling code here:
        baseErData.bs_R = bs_R.getSelectedIndex();
    }//GEN-LAST:event_bs_RActionPerformed

    private void do_bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_bsActionPerformed
        // TODO add your handling code here:
        baseErData.do_BS = do_bs.getSelectedIndex();
    }//GEN-LAST:event_do_bsActionPerformed

    private void bi_valueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bi_valueFocusLost
        // TODO add your handling code here:
        baseErData.bi = Double.parseDouble(bi_value.getText());
    }//GEN-LAST:event_bi_valueFocusLost

    private void han_aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_han_aFocusLost
        // TODO add your handling code here:
        baseErData.a = Double.parseDouble(han_a.getText());
    }//GEN-LAST:event_han_aFocusLost

    private void han_bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_han_bFocusLost
        // TODO add your handling code here:
        baseErData.b = Double.parseDouble(han_b.getText());
    }//GEN-LAST:event_han_bFocusLost

    public BaseErData getSelectData()
    {
        return this.baseErData;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bi_value;
    private javax.swing.JComboBox<String> bs_L;
    private javax.swing.JComboBox<String> bs_R;
    private javax.swing.JComboBox<String> do_bs;
    private javax.swing.JTextField han_a;
    private javax.swing.JTextField han_b;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> pt_L;
    private javax.swing.JComboBox<String> pt_R;
    // End of variables declaration//GEN-END:variables
}
