/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.newER;

import config.Config;
import mvc.controller.Controller;

/**
 *
 * @author wuxianshikong
 */
public class ErSetConPanel extends javax.swing.JPanel {
    Controller mainController;
    ErFrame erFrame;
    /**
     * Creates new form ErSetConPanel
     */
    public ErSetConPanel() {
        initComponents();
        erConJPanel1.bs_do.setText("买入");
        erConJPanel1.bs = Config.BUY_ID;
        erConJPanel2.bs_do.setText("卖出");
        erConJPanel2.bs = Config.SELL_ID;
        erConJPanel1.setMainController(this.mainController,this);
        erConJPanel2.setMainController(this.mainController,this);
    }
    public void setMainController(Controller mainController,ErFrame erFrame)
    {
        this.mainController = mainController;
        this.erFrame = erFrame;
        erConJPanel1.setMainController(this.mainController,this);
        erConJPanel2.setMainController(this.mainController,this);
    }
    public void updateSuperUI()
    {
        this.erFrame.upDateListData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        erConJPanel1 = new mvc.view.newER.ErConJPanel();
        erConJPanel2 = new mvc.view.newER.ErConJPanel();
        pt = new javax.swing.JComboBox<>();

        jTabbedPane1.addTab("买入", erConJPanel1);
        jTabbedPane1.addTab("卖出", erConJPanel2);

        pt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ok中国", "ok国际", "火币" }));
        pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mvc.view.newER.ErConJPanel erConJPanel1;
    private mvc.view.newER.ErConJPanel erConJPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JComboBox<String> pt;
    // End of variables declaration//GEN-END:variables
}
