/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.mainFrame;

import base.BaseNode;
import base.BaseUserInfo;
import config.Config;
import mvc.controller.Controller;
import mvc.model.HuoBIData;
import mvc.model.ModelBase;
import mvc.model.OkCoinCnData;
import mvc.model.OkCoinComData;

/**
 *
 * @author wuxianshikong
 */
public class PtJPanel extends javax.swing.JPanel implements BaseNode{
    /**
     * Creates new form PtJPanel
     */
    public PtJPanel() {
        initComponents();
        bSPTPanel1.setBSPanel(Config.BUY_ID);
        bSPTPanel2.setBSPanel(Config.SELL_ID);
        buyPanel1.setSuper(this,Config.BUY_ID);
        buyPanel2.setSuper(this,Config.BUY_ID);
        buyPanel3.setSuper(this,Config.BUY_ID);
        buyPanel4.setSuper(this,Config.BUY_ID);
        buyPanel5.setSuper(this,Config.BUY_ID);
        sellPanel1.setSuper(this,Config.SELL_ID);
        sellPanel2.setSuper(this,Config.SELL_ID);
        sellPanel3.setSuper(this,Config.SELL_ID);
        sellPanel4.setSuper(this,Config.SELL_ID);
        sellPanel5.setSuper(this,Config.SELL_ID);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        tabbedPabel = new javax.swing.JTabbedPane();
        buyPanel = new javax.swing.JPanel();
        bSPTPanel1 = new mvc.view.mainFrame.BSJPanel();
        sellPanel = new javax.swing.JPanel();
        bSPTPanel2 = new mvc.view.mainFrame.BSJPanel();
        jPanel3 = new javax.swing.JPanel();
        sellPanel5 = new mvc.view.mainFrame.PtListJPanel();
        sellPanel4 = new mvc.view.mainFrame.PtListJPanel();
        sellPanel3 = new mvc.view.mainFrame.PtListJPanel();
        sellPanel2 = new mvc.view.mainFrame.PtListJPanel();
        sellPanel1 = new mvc.view.mainFrame.PtListJPanel();
        buyPanel1 = new mvc.view.mainFrame.PtListJPanel();
        buyPanel2 = new mvc.view.mainFrame.PtListJPanel();
        buyPanel3 = new mvc.view.mainFrame.PtListJPanel();
        buyPanel4 = new mvc.view.mainFrame.PtListJPanel();
        buyPanel5 = new mvc.view.mainFrame.PtListJPanel();

        setBackground(new java.awt.Color(0, 204, 0));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        titleLabel.setText("okcoin");

        tabbedPabel.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout buyPanelLayout = new javax.swing.GroupLayout(buyPanel);
        buyPanel.setLayout(buyPanelLayout);
        buyPanelLayout.setHorizontalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyPanelLayout.createSequentialGroup()
                .addComponent(bSPTPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buyPanelLayout.setVerticalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bSPTPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabbedPabel.addTab("买入", buyPanel);

        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);
        sellPanelLayout.setHorizontalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addComponent(bSPTPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sellPanelLayout.setVerticalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bSPTPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabbedPabel.addTab("卖出", sellPanel);

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sellPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setBSData(int bs,double value,double num)
    {
        if(bs == Config.BUY_ID)
        {
            bSPTPanel1.setBSData(value,num);
            tabbedPabel.setSelectedComponent(buyPanel);
        }
        else
        {
            bSPTPanel2.setBSData(value,num);
            tabbedPabel.setSelectedComponent(sellPanel);
        }
        
    }
    public void setPt(int pt,Controller con)
    {
        this.mainController = con;
        this.ptID = pt;
        titleLabel.setText(Config.getNameByPlat(pt));
        this.bSPTPanel1.setSuperPanel(this);
        this.bSPTPanel2.setSuperPanel(this);
    }
    /**
     * 平台id
     */
    public int ptID;
    /**
     * 主控制器
     */
    public Controller mainController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mvc.view.mainFrame.BSJPanel bSPTPanel1;
    private mvc.view.mainFrame.BSJPanel bSPTPanel2;
    private javax.swing.JPanel buyPanel;
    public mvc.view.mainFrame.PtListJPanel buyPanel1;
    public mvc.view.mainFrame.PtListJPanel buyPanel2;
    public mvc.view.mainFrame.PtListJPanel buyPanel3;
    public mvc.view.mainFrame.PtListJPanel buyPanel4;
    public mvc.view.mainFrame.PtListJPanel buyPanel5;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel sellPanel;
    public mvc.view.mainFrame.PtListJPanel sellPanel1;
    public mvc.view.mainFrame.PtListJPanel sellPanel2;
    public mvc.view.mainFrame.PtListJPanel sellPanel3;
    public mvc.view.mainFrame.PtListJPanel sellPanel4;
    public mvc.view.mainFrame.PtListJPanel sellPanel5;
    public javax.swing.JTabbedPane tabbedPabel;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    public Boolean bsRequest(int bs,double value,double num)
    {
        return mainController.bsRequest(bs, value, num, ptID);
    }
    public void upDateHuobi(ModelBase medol)
    {
        HuoBIData medelData = (HuoBIData)medol;
        if(medelData.tickerBuyData.length < 5 && medelData.tickerSellData.length < 5)
        {
            return;
        }
        buyPanel1.id.setText("买一");
        buyPanel1.value.setText(medelData.tickerBuyData[0].value+"");
        buyPanel1.num.setText(medelData.tickerBuyData[0].num+"");

        buyPanel2.id.setText("买二");
        buyPanel2.value.setText(medelData.tickerBuyData[1].value+"");
        buyPanel2.num.setText(medelData.tickerBuyData[1].num+"");

        buyPanel3.id.setText("买三");
        buyPanel3.value.setText(medelData.tickerBuyData[2].value+"");
        buyPanel3.num.setText(medelData.tickerBuyData[2].num+"");

        buyPanel4.id.setText("买四");
        buyPanel4.value.setText(medelData.tickerBuyData[3].value+"");
        buyPanel4.num.setText(medelData.tickerBuyData[3].num+"");

        buyPanel5.id.setText("买五");
        buyPanel5.value.setText(medelData.tickerBuyData[4].value+"");
        buyPanel5.num.setText(medelData.tickerBuyData[4].num+"");
        
        sellPanel1.id.setText("卖一");
        sellPanel1.value.setText(medelData.tickerSellData[4].value+"");
        sellPanel1.num.setText(medelData.tickerSellData[4].num+"");

        sellPanel2.id.setText("卖二");
        sellPanel2.value.setText(medelData.tickerSellData[3].value+"");
        sellPanel2.num.setText(medelData.tickerSellData[3].num+"");

        sellPanel3.id.setText("卖三");
        sellPanel3.value.setText(medelData.tickerSellData[2].value+"");
        sellPanel3.num.setText(medelData.tickerSellData[2].num+"");

        sellPanel4.id.setText("卖四");
        sellPanel4.value.setText(medelData.tickerSellData[1].value+"");
        sellPanel4.num.setText(medelData.tickerSellData[1].num+"");

        sellPanel5.id.setText("卖五");
        sellPanel5.value.setText(medelData.tickerSellData[0].value+"");
        sellPanel5.num.setText(medelData.tickerSellData[0].num+"");
        
    }
    public void updateOkCoinCn(ModelBase medol)
    {
    	OkCoinCnData medelData = (OkCoinCnData)medol;
         if(medelData.verTickerSellData.size() < 5 && medelData.verTickerBuyData.size() < 5)
         {
             return;
         }
         buyPanel1.id.setText("买一");
         buyPanel1.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-1).value+"");
         buyPanel1.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-1).num+"");

         buyPanel2.id.setText("买二");
         buyPanel2.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-2).value+"");
         buyPanel2.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-2).num+"");

         buyPanel3.id.setText("买三");
         buyPanel3.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-3).value+"");
         buyPanel3.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-3).num+"");

         buyPanel4.id.setText("买四");
         buyPanel4.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-4).value+"");
         buyPanel4.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-4).num+"");

         buyPanel5.id.setText("买五");
         buyPanel5.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-5).value+"");
         buyPanel5.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-5).num+"");
         
         sellPanel1.id.setText("卖一");
         sellPanel1.value.setText(medelData.verTickerSellData.get(0).value+"");
         sellPanel1.num.setText(medelData.verTickerSellData.get(0).num+"");

         sellPanel2.id.setText("卖二");
         sellPanel2.value.setText(medelData.verTickerSellData.get(1).value+"");
         sellPanel2.num.setText(medelData.verTickerSellData.get(1).num+"");

         sellPanel3.id.setText("卖三");
         sellPanel3.value.setText(medelData.verTickerSellData.get(2).value+"");
         sellPanel3.num.setText(medelData.verTickerSellData.get(2).num+"");

         sellPanel4.id.setText("卖四");
         sellPanel4.value.setText(medelData.verTickerSellData.get(3).value+"");
         sellPanel4.num.setText(medelData.verTickerSellData.get(3).num+"");

         sellPanel5.id.setText("卖五");
         sellPanel5.value.setText(medelData.verTickerSellData.get(4).value+"");
         sellPanel5.num.setText(medelData.verTickerSellData.get(4).num+"");
    }
    public void updateOkCoinCom(ModelBase medol)
    {
    	OkCoinComData medelData = (OkCoinComData)medol;
         if(medelData.verTickerSellData.size() < 5 && medelData.verTickerBuyData.size() < 5)
         {
             return;
         }
         buyPanel1.id.setText("买一");
         buyPanel1.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-1).value+"");
         buyPanel1.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-1).num+"");

         buyPanel2.id.setText("买二");
         buyPanel2.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-2).value+"");
         buyPanel2.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-2).num+"");

         buyPanel3.id.setText("买三");
         buyPanel3.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-3).value+"");
         buyPanel3.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-3).num+"");

         buyPanel4.id.setText("买四");
         buyPanel4.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-4).value+"");
         buyPanel4.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-4).num+"");

         buyPanel5.id.setText("买五");
         buyPanel5.value.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-5).value+"");
         buyPanel5.num.setText(medelData.verTickerBuyData.get(medelData.verTickerBuyData.size()-5).num+"");
         
         sellPanel1.id.setText("卖一");
         sellPanel1.value.setText(medelData.verTickerSellData.get(0).value+"");
         sellPanel1.num.setText(medelData.verTickerSellData.get(0).num+"");

         sellPanel2.id.setText("卖二");
         sellPanel2.value.setText(medelData.verTickerSellData.get(1).value+"");
         sellPanel2.num.setText(medelData.verTickerSellData.get(1).num+"");

         sellPanel3.id.setText("卖三");
         sellPanel3.value.setText(medelData.verTickerSellData.get(2).value+"");
         sellPanel3.num.setText(medelData.verTickerSellData.get(2).num+"");

         sellPanel4.id.setText("卖四");
         sellPanel4.value.setText(medelData.verTickerSellData.get(3).value+"");
         sellPanel4.num.setText(medelData.verTickerSellData.get(3).num+"");

         sellPanel5.id.setText("卖五");
         sellPanel5.value.setText(medelData.verTickerSellData.get(4).value+"");
         sellPanel5.num.setText(medelData.verTickerSellData.get(4).num+"");
    }
    @Override
    public void update() {
        ModelBase medol = mainController.getModelData(ptID);
        if(ptID == Config.HUOBI)
        {
        	try
        	{
        		upDateHuobi(medol);
        	}
            catch(Exception e)
            {
            	
            }
        }
        else if(ptID == Config.OKCOINCN)
        {
        	try
        	{
        		updateOkCoinCn(medol);
        	}
            catch(Exception e)
            {
            	
            }
        	
        }
        else if(ptID == Config.OKCOINCOM)
        {
        	try
        	{
        		updateOkCoinCom(medol);
        	}
            catch(Exception e)
            {
            	
            }
        	
        }
    }

	public void updateUserInfo(BaseUserInfo infoData) {
		// TODO Auto-generated method stub
		bSPTPanel1.updateUserInfo(infoData);
		bSPTPanel2.updateUserInfo(infoData);
	}
}
