/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.balanceFrame;

import base.UserConBase;
import config.Config;
import mvc.controller.Controller;

/**
 *
 * @author wuxianshikong
 */
public class CellPanel extends javax.swing.JPanel {
    Controller mainControl;
    UserConBase userCheckData;
    FutureJFrame superaThis;
    public void resetUserConBase(UserConBase userCheckData)
    {
        this.userCheckData = userCheckData;
        if(this.userCheckData != null)
        {
            String typebs[] = {"现货","当周","次周","季度"};
            pt_L.setText(Config.getNameByPlat(userCheckData.platLeft + 1));
            type_L.setText(typebs[userCheckData.TypeMTLeft]+Config.getStringBS(userCheckData.BSStateLeft));
            pt_R.setText(Config.getNameByPlat(userCheckData.platRight + 1));
            type_R.setText(typebs[userCheckData.TypeMTRight]+Config.getStringBS(userCheckData.BSStateRight));
            do_LR.setText("左"+ Config.getStringBSDO(userCheckData.do_bs_L)+"右"+ Config.getStringBSDO(userCheckData.do_bs_R));
            compare.setText(Config.getHDStr(userCheckData.ComPareState));
            money.setText("" + userCheckData.money);
            limitMax.setText("" + userCheckData.limitMax);
            this.setVisible(true);
        }
        else
        {
            pt_L.setText("");
            type_L.setText("");
            pt_R.setText("");
            type_R.setText("");
            do_LR.setText("");
            compare.setText("");
            money.setText("");
            limitMax.setText("");
            this.setVisible(false);
        }
    }
    /**
     * Creates new form CellPanel
     */
    public CellPanel() {
        initComponents();
        resetUserConBase(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pt_L = new javax.swing.JLabel();
        type_L = new javax.swing.JLabel();
        pt_R = new javax.swing.JLabel();
        type_R = new javax.swing.JLabel();
        do_LR = new javax.swing.JLabel();
        compare = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        limitMax = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));

        pt_L.setText("okCoin中国");

        type_L.setText("期货现价");

        pt_R.setText("okCoin中国");
        pt_R.setToolTipText("");

        type_R.setText("期货现价");

        do_LR.setText("左买右卖");

        compare.setText("大于");

        money.setText("10000");

        jButton1.setText("撤销");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        limitMax.setText("10000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(pt_L, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compare, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(do_LR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitMax, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt_L)
                    .addComponent(type_L)
                    .addComponent(pt_R)
                    .addComponent(type_R)
                    .addComponent(do_LR)
                    .addComponent(compare)
                    .addComponent(money)
                    .addComponent(jButton1)
                    .addComponent(limitMax)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.superaThis.mainControl.removeProcess(this.userCheckData.U_id);
        this.superaThis.updateUIList();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compare;
    private javax.swing.JLabel do_LR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel limitMax;
    private javax.swing.JLabel money;
    private javax.swing.JLabel pt_L;
    private javax.swing.JLabel pt_R;
    private javax.swing.JLabel type_L;
    private javax.swing.JLabel type_R;
    // End of variables declaration//GEN-END:variables

    void resetUserConBase(UserConBase userCheckData, FutureJFrame aThis) {
        superaThis = aThis;
        this.resetUserConBase(userCheckData);
    }
}
